import path from 'path';
import fs from 'fs';

let appInstance: any = null;

try {
  const serverBundlePath = path.resolve(process.cwd(), 'dist', 'server.cjs');
  if (fs.existsSync(serverBundlePath)) {
    // Require the pre-bundled Express application generated by esbuild
    const serverModule = require(serverBundlePath);
    appInstance = serverModule.default || serverModule.app || serverModule;
  } else {
    console.error(`[API Entry] Built server bundle not found at: ${serverBundlePath}`);
  }
} catch (error: any) {
  console.error('[API Entry] Critical error while loading dist/server.cjs bundle:');
  console.error(error?.stack || error);
}

// Export handler function compatible with Vercel serverless runtime
export default function handler(req: any, res: any) {
  if (appInstance && typeof appInstance === 'function') {
    return appInstance(req, res);
  }

  // Fallback: If bundle fails to load for any reason, serve index.html directly
  try {
    const distHtmlPath = path.resolve(process.cwd(), 'dist', 'index.html');
    if (fs.existsSync(distHtmlPath)) {
      const html = fs.readFileSync(distHtmlPath, 'utf-8');
      return res.status(200).setHeader('Content-Type', 'text/html').send(html);
    }
  } catch (fallbackErr) {
    console.error('[API Entry] Fallback static HTML error:', fallbackErr);
  }

  return res.status(500).json({
    error: 'SERVER_BUNDLE_UNAVAILABLE',
    message: 'Express application bundle could not be initialized.',
  });
}

